### ISSUE TITLE
Configure layout

### ISSUE THREAD

**Issue by landru29** [rpocklin/angular-timeline#10]
Hi,

I propose you some improvements to customize layout :
https://github.com/landru29/angular-timeline/blob/master/src/timeline-event-directive.js

2 attributes are available on timeline-event directive
- **side** : 'right' or 'left' to display all elements on the same side
- **distribute** : 'right' or 'left' to alternate elements right/left (the value define where the first element will be displayed)

the attributes are watched, so that they be lived changed

**Comment by rpocklin** [comment]
Thanks landru.

I see you've made changes to your forked version of this, it's probably best to create a pull request instead of an issue, that way your code changes will show up, along with test passing status and we can talk about the changes there.  An issue is more for a potential problem or question.  I'm more than happy to look at your PR though.

**Comment by henry74** [comment]
+1
